version: '3.9'
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sreality_db
      PGDATA: /data/postgres
  server:
    container_name: server
    environment:
      DB_SERVER: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: sreality_db
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  client:
    container_name: client
    environment:
      REACT_APP_API_URL: http://localhost:4000
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      
  
